ethermap/maps/maps_markers/urls.py
from django.urls import path

from . import views

app_name = "maps_markers"

urlpatterns = (
    path("xhr/<slug:map_slug>/add", views.xhr_add, name="xhr-add"),
    path(
        "xhr/<slug:map_slug>/<slug:slug>/edit", views.xhr_edit, name="xhr-edit"
    ),
    path(
        "xhr/<slug:map_slug>/<slug:slug>/delete",
        views.xhr_delete,
        name="xhr-delete",
    ),
)

ethermap/maps/urls.py
from django.urls import path, include

from . import views

app_name = "maps"

urlpatterns = (
    path("", include("ethermap.maps.maps_markers.urls", namespace="markers")),
    path("", views.create, name="create"),
    path("m/<slug:slug>", views.view, name="view"),
    path("m/<slug:slug>.json", views.export, name="export"),
    path("xhr/<slug:slug>", views.xhr_data, name="xhr-data"),
    path("xhr/<slug:slug>/settings", views.xhr_settings, name="xhr-settings"),
    path("xhr/<slug:slug>/password", views.xhr_password, name="xhr-password"),
    path(
        "xhr/<slug:slug>/save-center",
        views.xhr_save_center,
        name="xhr-save-center",
    ),
    path(
        "xhr/<slug:slug>/authenticate",
        views.xhr_authenticate,
        name="xhr-authenticate",
    ),
)

ethermap/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.views.static import serve

urlpatterns = (
    url("", include("ethermap.maps.urls", namespace="maps")),
    url(r"", include("ethermap.static.urls", namespace="static")),
)

if settings.DEBUG:
    urlpatterns += (
        url(
            r"^(?P<path>favicon.ico)$",
            serve,
            {"document_root": settings.STATIC_ROOT},
        ),
        url(
            r"^storage/(?P<path>.*)$",
            serve,
            {"document_root": settings.MEDIA_ROOT},
        ),
    )

ethermap/maps/maps_markers/models.py
from django.db import models
from django.conf import settings
from django.utils.crypto import get_random_string


class Marker(models.Model):
    map = models.ForeignKey(
        "maps.Map", on_delete=models.CASCADE, related_name="markers"
    )

    slug = models.CharField(max_length=12, default=get_random_string)

    lat = models.CharField(max_length=255)
    lng = models.CharField(max_length=255)

    icon = models.CharField(
        max_length=64, choices=settings.ICONS, default=settings.ICONS[0][0]
    )

    title = models.CharField(max_length=255, blank=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return "pk={0.pk} map={0.map_id} title={0.title!r}".format(self)

    class Meta:
        unique_together = (("map", "slug"),)

ethermap/maps/models.py
import functools

from django.db import models
from django.urls import reverse
from django.utils.crypto import get_random_string

MAP_LAYERS = (
    ("mapbox/streets-v11", "Colour"),
    ("mapbox/light-v9", "Greyscale"),
)


class Map(models.Model):
    title = models.CharField(max_length=255, blank=True)

    slug = models.CharField(
        unique=True,
        default=functools.partial(
            get_random_string, 20, "abcdefghjkmnpqrstwxyz3479"
        ),
        max_length=64,
    )

    layer = models.CharField(
        choices=MAP_LAYERS, default=MAP_LAYERS[0][0], max_length=128,
    )

    password = models.CharField(max_length=128, blank=True)

    # If true and a password is set, require the password to view the map.
    private = models.BooleanField(default=False, blank=True)

    lat = models.CharField(max_length=255)
    lng = models.CharField(max_length=255)
    zoom = models.IntegerField(default=14)

    cachebust = models.CharField(max_length=12, default=get_random_string)

    def __str__(self):
        return "pk={0.pk}".format(self)

    def get_absolute_url(self):
        return reverse("maps:view", args=(self.slug,))

    def markers_changed(self):
        self.cachebust = get_random_string()

        if self.markers.count() != 1:
            self.save(update_fields=("cachebust",))
            return

        marker = self.markers.get()

        self.lat = marker.lat
        self.lng = marker.lng
        self.zoom = Map._meta.get_field("zoom").default

        self.save()

ethermap/maps/forms.py
import emoji
import slugify

from django import forms
from django.contrib.auth.hashers import check_password, make_password

from .models import Map


class CreateForm(forms.ModelForm):
    class Meta:
        model = Map
        fields = ("title",)

    def save(self):
        slug = slugify.slugify(
            emoji.demojize(self.cleaned_data["title"].strip()),
            max_length=Map._meta.get_field("slug").max_length,
        )

        if slug:
            try:
                return Map.objects.get(slug=slug)
            except Map.DoesNotExist:
                pass

        instance = super().save(commit=False)
        if slug:
            instance.slug = slug
        instance.save()

        return instance


class SettingsForm(forms.ModelForm):
    class Meta:
        model = Map
        fields = ("title", "layer")

    def save(self):
        instance = super().save()
        instance.markers_changed()
        return instance


class PasswordForm(forms.ModelForm):
    password1 = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = Map
        fields = ("private",)

    def clean(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")

        if password1 != password2:
            self.add_error("password2", "Passwords do not match")

        return self.cleaned_data

    def save(self, request):
        instance = super().save(commit=False)

        hashed = make_password(self.cleaned_data["password1"])
        instance.password = hashed

        # Grant the user access
        request.session[instance.slug] = hashed

        instance.save()

        instance.markers_changed()

        return instance


class SaveCenterForm(forms.ModelForm):
    class Meta:
        model = Map
        fields = ("lat", "lng", "zoom")


class AuthenticationForm(forms.Form):
    password = forms.CharField()

    def __init__(self, map, *args, **kwargs):
        self.map = map

        super().__init__(*args, **kwargs)

    def clean_password(self):
        val = self.cleaned_data["password"]

        if not check_password(val, self.map.password):
            raise forms.ValidationError("Invalid password")

        return val

    def save(self, request):
        # Store the password hash in the session for authentication
        request.session[self.map.slug] = self.map.password

ethermap/maps/maps_markers/forms.py
from django import forms

from .models import Marker


class CreateMarkerForm(forms.ModelForm):
    class Meta:
        model = Marker
        fields = ("lat", "lng", "title", "description", "icon")


class EditMarkerForm(forms.ModelForm):
    class Meta:
        model = Marker
        fields = ("title", "description", "icon")

ethermap/maps/maps_markers/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from django.views.decorators.http import require_POST

from ..utils import get_map

from .forms import CreateMarkerForm, EditMarkerForm


def xhr_add(request, map_slug):
    map = get_map(request, slug=map_slug)

    if request.method == "POST":
        form = CreateMarkerForm(request.POST)

        if form.is_valid():
            marker = form.save(commit=False)
            marker.map = map
            marker.save()
            map.markers_changed()

        return JsonResponse(form.errors.get_json_data())

    form = CreateMarkerForm()

    return render(
        request, "maps/xhr_add_edit_marker.html", {"map": map, "form": form}
    )


def xhr_edit(request, map_slug, slug):
    map = get_map(request, slug=map_slug)
    marker = get_object_or_404(map.markers, slug=slug)

    if request.method == "POST":
        form = EditMarkerForm(request.POST, instance=marker)

        if form.is_valid():
            form.save()
            map.markers_changed()

        return JsonResponse(form.errors.get_json_data())

    form = EditMarkerForm(instance=marker)

    return render(
        request,
        "maps/xhr_add_edit_marker.html",
        {"map": map, "form": form, "marker": marker},
    )


@require_POST
def xhr_delete(request, map_slug, slug):
    map = get_map(request, slug=map_slug)
    marker = get_object_or_404(map.markers, slug=slug)

    marker.delete()

    map.markers_changed()

    return JsonResponse({})

ethermap/maps/views.py
from django.conf import settings
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import PermissionDenied
from django.template.loader import render_to_string
from django.views.decorators.csrf import ensure_csrf_cookie
from django.views.decorators.http import require_POST

from .forms import (
    CreateForm,
    AuthenticationForm,
    SettingsForm,
    PasswordForm,
    SaveCenterForm,
)
from .utils import get_map, can_edit
from .models import Map


def create(request):
    if request.method == "POST":
        form = CreateForm(request.POST)

        if form.is_valid():
            map = form.save()

            return redirect(map)
    else:
        form = CreateForm()

    return render(request, "maps/create.html", {"form": form})


@ensure_csrf_cookie
def view(request, slug):
    map = get_object_or_404(Map, slug=slug)
    form = AuthenticationForm(map)
    template = "maps/edit.html"

    try:
        template = "maps/edit.html"
        get_map(request, slug=slug, map=map)
    except PermissionDenied:
        template = "maps/view.html"

        if map.private:
            template = "maps/login.html"

    return render(request, template, {"map": map, "form": form})


def xhr_data(request, slug):
    map = get_map(request, slug=slug, login_required=False)

    # Don't update the client if there have been no changes
    if request.GET.get("cachebust") == str(map.cachebust):
        return JsonResponse({})

    show_edit_controls = can_edit(request, map)

    markers = [
        {
            "lat": x.lat,
            "lng": x.lng,
            "icon": x.icon,
            "title": x.title,
            "html": render_to_string(
                "maps/include_marker.html",
                {"marker": x, "show_edit_controls": show_edit_controls},
            ),
        }
        for x in map.markers.all()
    ]

    return JsonResponse(
        {
            "map": {
                "lat": map.lat,
                "lng": map.lng,
                "zoom": map.zoom,
                "layer": map.layer,
                "brand": render_to_string(
                    "maps/include_brand.html", {"map": map}
                ),
                "title": render_to_string(
                    "maps/include_title.html", {"map": map}
                ),
            },
            "markers": markers,
            "cachebust": map.cachebust,
            "mapbox_access_token": settings.MAPBOX_ACCESS_TOKEN,
        }
    )


def export(request, slug):
    map = get_map(request, slug=slug, login_required=False)

    features = [
        {
            "type": "Feature",
            "properties": {"name": x.title, "description": x.description},
            "geometry": {
                "type": "Point",
                "coordinates": [float(x.lng), float(x.lat)],
            },
            "_ethermap": {"icon": x.icon},
        }
        for x in map.markers.all()
    ]

    return JsonResponse(
        {
            "type": "FeatureCollection",
            "features": features,
            "_ethermap": {
                "lat": map.lat,
                "lng": map.lng,
                "zoom": map.zoom,
                "layer": map.layer,
                "title": map.title,
            },
        },
        json_dumps_params={"indent": 2},
    )


def xhr_authenticate(request, slug):
    map = get_object_or_404(Map, slug=slug)

    if request.method == "POST":
        form = AuthenticationForm(map, request.POST)

        if form.is_valid():
            form.save(request)

        return JsonResponse(form.errors.get_json_data())

    form = AuthenticationForm(map)

    return render(
        request, "maps/xhr_authenticate.html", {"map": map, "form": form}
    )


def xhr_settings(request, slug):
    map = get_map(request, slug=slug)

    if request.method == "POST":
        form = SettingsForm(request.POST, instance=map)

        if form.is_valid():
            form.save()

        return JsonResponse(form.errors.get_json_data())

    form = SettingsForm(instance=map)

    return render(
        request, "maps/xhr_settings.html", {"map": map, "form": form}
    )


def xhr_password(request, slug):
    map = get_map(request, slug=slug)

    if map.password:
        raise PermissionDenied("Cannot edit existing password.")

    if request.method == "POST":
        form = PasswordForm(request.POST, instance=map)

        if form.is_valid():
            form.save(request)

        return JsonResponse(form.errors.get_json_data())

    form = PasswordForm(instance=map)

    return render(
        request, "maps/xhr_password.html", {"map": map, "form": form}
    )


@require_POST
def xhr_save_center(request, slug):
    map = get_map(request, slug=slug)

    form = SaveCenterForm(request.POST, instance=map)

    if form.is_valid():
        form.save()

    return JsonResponse(form.errors.get_json_data())

templates/maps/edit.html
{% extends "maps/view.html" %}

{% block body_classes %}{{ block.super }} f_maps_edit{% endblock %}

{% block rightnav %}

  <div class="nav-item mr-md-2 mt-1 mt-sm-0">
    <button
      type="button"
      data-url="{% url "maps:xhr-settings" map.slug %}"
      class="btn btn-block btn-secondary js-settings"
      title="Map settings (x)"
    >Map settings</button>
  </div>
  <div class="nav-item mr-md-2 mt-1 mt-sm-0">
    <button
      data-url="{% url "maps:xhr-save-center" map.slug %}"
      data-default="Save current view"
      data-saving="Saving&hellip;"
      data-saved="Saved"
      type="button"
      class="nav-item btn btn-block btn-secondary js-save-center"
      title="Save current view (c)"
    >Save current view</button>
  </div>
  <div class="nav-item mr-md-2 mt-1 mt-sm-0">
    <button
      type="button"
      class="btn btn-block btn-secondary"
      data-toggle="modal" data-target="#share-modal"
      title="Share (S)"
    >Share<span class="d-inline d-sm-none"> map</span></button>
  </div>
  <div class="nav-item mr-md-2 mt-1 mt-sm-0">
    <button
      type="button"
      class="btn btn-block btn-secondary"
      data-toggle="modal" data-target="#about-modal"
      title="About (?)"
    >About <span class="d-inline d-sm-none"> Ethermap</span></button>
  </div>
  <div class="nav-item mr-md-2 mt-1 mt-sm-0">
    <button
      type="button"
      class="btn btn-block btn-secondary js-search"
      title="Search (s)"
    >Search</button>
  </div>
  <div class="nav-item mt-1 mt-sm-0">
    <button
      type="button"
      data-url="{% url "maps:markers:xhr-add" map.slug %}"
      data-default="&#x2795; Add marker"
      data-adding="Click to add a marker&hellip;"
      class="btn btn-block btn-primary js-add-marker"
      title="Add marker (a)"
    ><span class="d-none d-sm-inline">&#x2795; </span>Add marker</button>
  </div>
{% endblock %}

templates/maps/include_brand.html
<i class="icon-map m-auto pr-3"></i>Ethermap{% if map.title %}: {{ map.title }}{% endif %}

templates/maps/include_marker.html
<div class="marker">
  {% if marker.title %}
  <h6>{{ marker.title }}</h6>
  {% endif %}

  {{ marker.description|preprocess_markdown|markdown:"break-on-newline,nofollow" }}

  {% if show_edit_controls %}
  <div class="btn-group btn-group-sm">
    <a
      href="#"
      class="btn btn-primary js-edit-marker"
      data-url="{% url "maps:markers:xhr-edit" marker.map.slug marker.slug %}"
    >Edit</a>
    <a
      href="#"
      class="btn btn-danger js-delete-marker"
      data-url="{% url "maps:markers:xhr-delete" marker.map.slug marker.slug %}"
      data-confirm="Are you sure you wish to remove this marker?"
    >Delete</a>
    {% endif %}
  </div>
</div>

templates/maps/include_title.html
{{ map.title|default:"No title" }} &mdash; ethermap

templates/maps/login.html
{% extends "base/base.html" %}

{% block body_classes %}{{ block.super }} f_maps_view f_maps_login{% endblock %}

{% block body %}
<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="login-modal-label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="login-modal-label">Enter map password</h5>
      </div>
      <div class="modal-body">
        <form method="POST" action="">
          <div class="form-group col-md-12">
            <label class="col-form-label" for="{{ form.password.id_for_label }}">
              Password
            </label>
            <input
              id="{{ form.password.id_for_label }}"
              type="password"
              class="form-control"
              name="{{ form.password.html_name }}"
              value="{{ form.password.value|default:"" }}"
              maxlength="{{ form.password.field.max_length|default:"" }}"
              placeholder=""
              {% if form.password.field.required %}required{% endif %}
            >
            <small class="form-text text-muted">
              Enter the map's password to be able to view it.
            </small>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button
          type="button"
          data-url="{% url "maps:xhr-authenticate" map.slug %}"
          class="btn btn-primary js-authenticate"
        >Login</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/maps/view.html
{% extends "base/generic_base.html" %}

{% block body_classes %}{{ block.super }} f_maps_view{% endblock %}

{% block extrahead %}
{{ block.super }}

<link rel="stylesheet" href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css" />
<link rel="stylesheet" type="text/css" href="https://cdn-geoweb.s3.amazonaws.com/esri-leaflet-geocoder/0.0.1-beta.5/esri-leaflet-geocoder.css">
{% endblock %}

{% block script %}
{{ block.super }}
<script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
  integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og==" crossorigin=""></script>
<script src="https://cdn-geoweb.s3.amazonaws.com/esri-leaflet/0.0.1-beta.5/esri-leaflet.js"></script>
<script src="https://cdn-geoweb.s3.amazonaws.com/esri-leaflet-geocoder/0.0.1-beta.5/esri-leaflet-geocoder.js"></script>
<script src="{% static "js/mousetrap.js" %}"></script>
<script>
  var icons = {
    {% for x, y in settings.ICONS %}
    {% with "img/f_maps_view/marker-"|add:x|add:".png" as url %}
    "{{ x|escapejs }}": {
      "url": "{% static url %}",
      "name": "{{ y|escapejs }}"
    }{% if not forloop.last %},{% endif %}
    {% endwith %}
    {% endfor %}
  };

  $.sync();
</script>
{% endblock %}

{% block body %}

<div class="container js-progress" style="height: 100%;">
  <div class="row px-5" style="height: 100%;">
    <div class="text-center align-self-center" style="width: 100%">
      <div class="progress">
        <div class="progress-bar progress-bar-striped progress-bar-animated" style="width: 100%"></div>
      </div>
    </div>
  </div>
</div>

<nav class="navbar navbar-expand-md navbar-light">
  <a class="navbar-brand" href="{% url "maps:create" %}"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbar-collapse">
    <ul class="navbar-nav mr-auto">
    </ul>
    <div class="navbar-nav fade">
      {% block rightnav %}
      <div class="nav-item mr-md-2 mt-1 mt-sm-0">
        <button
          type="button"
          data-url="{% url "maps:xhr-authenticate" map.slug %}"
          class="btn btn-block btn-outline-secondary js-edit"
          title="Edit (e)"
        >Enter password to edit map</button>
      </div>
      <div class="nav-item mr-md-2 mt-1 mt-sm-0">
        <button
          type="button"
          class="btn btn-block btn-secondary"
          data-toggle="modal" data-target="#share-modal"
          title="Share (S)"
        >Share<span class="d-inline d-sm-none"> map</span></button>
      </div>
      <div class="nav-item mr-md-2 mt-1 mt-sm-0">
        <button
          type="button"
          class="btn btn-block btn-secondary"
          data-toggle="modal" data-target="#about-modal"
          title="About (?)"
        >About<span class="d-inline d-sm-none"> Ethermap</span></button>
      </div>
      {% endblock %}
    </div>
  </div>
</nav>

<div
  id="mapid"
  class="d-none"
  data-url="{% url "maps:xhr-data" map.slug %}"
></div>

<div class="modal fade" id="about-modal" tabindex="-1" role="dialog" aria-labelledby="about-modal-label" aria-hidden="true">
  <div class="modal-dialog modal-lg modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="about-modal-label">About Ethermap</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p class="lead my-3">
          Ethermap is site that allows anyone from anywhere in the world to
          <strong>create, view and share</strong> locations with their friends.
        </p>

        <p>
          Ethermap is free to use for everyone and free to use for any purpose,
          including commercially. Ethermap is also free to share with others,
          free to study <a href="https://gitlab.com/ethermap/ethermap">Ethermap's source code</a>
          and even free to make your own versions and modifications.
        </p>

        <p>
          Ethermap has no adverts and never will have, it's just a financially
          sustainable service that is provided to improve the world. However,
          if you find it useful, please consider becoming a
          <a href="https://sfconservancy.org/supporter/">supporter of the Software
          Freedom Conservancy</a>, a not-for-profit charity that promotes
          improves and develops ethical technology.
        </p>

        <p class="text-center">
          <a
            href="{% url "maps:create" %}"
            class="btn btn-primary"
            target="_new"
          >Create my own map</a>
        </p>

        <p class="text-center">
          <strong>Spot a problem? Have a feature request? Want to contribute? Please review
          <a href="https://gitlab.com/ethermap/ethermap/issues" target="_new">our outstanding issues</a>.
          </strong>
        </p>

        <p class="text-muted text-center">
          <small>
          <a href="{% url "static:privacy" %}">Privacy policy</a>
          &bull;
          <a href="{% url "static:terms" %}">Terms of service</a>
          <br>
          Copyright &copy; 2018&mdash;{% now "Y" %}
          <a href="https://chris-lamb.co.uk">Chris Lamb</a>.
          <br>
          Released under the terms of the
          <a href="https://www.gnu.org/licenses/agpl-3.0.en.html">GNU AGPL</a>.
          (<a href="https://gitlab.com/ethermap/ethermap">Source</a>)
          </small>
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="share-modal" tabindex="-1" role="dialog" aria-labelledby="share-modal-label" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="share-modal-label">Share map</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="input-group">
          <input
            readonly
            type="text"
            class="form-control disabled js-uri"
            value="{{ request.build_absolute_uri }}"
          >
          <div class="input-group-append">
            <button
              type="button"
              class="btn btn-secondary js-copy-to-clipboard"
            >Copy to clipboard</button>
          </div>
        </div>
        <small class="form-text text-muted">
          Share this map with your friends. Anyone with the URL still be able
          to view it.
        </small>
      </div>
      <div class="modal-footer">
        <a href="{% url "maps:export" map.slug %}" class="btn btn-secondary">Export GeoJSON</a>
        <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/maps/xhr_authenticate.html
<div class="modal fade" id="authenticate-modal" tabindex="-1" role="dialog" aria-labelledby="authenticate-modal-label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="authenticate-modal-label">Enter map password</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST" action="">
          <div class="form-group col-md-12">
            <label class="col-form-label" for="{{ form.password.id_for_label }}">
              Password
            </label>
            <input
              id="{{ form.password.id_for_label }}"
              type="password"
              class="form-control"
              name="{{ form.password.html_name }}"
              value="{{ form.password.value|default:"" }}"
              maxlength="{{ form.password.field.max_length|default:"" }}"
              placeholder=""
              {% if form.password.field.required %}required{% endif %}
            >
            <small class="form-text text-muted">
              Enter the map's password to be able to edit it. Anyone with the
              URL of this map can still view it.
            </small>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button
          type="button"
          data-url="{% url "maps:xhr-authenticate" map.slug %}"
          class="btn btn-primary js-authenticate"
        >Authenticate</button>
      </div>
    </div>
  </div>
</div>

templates/maps/xhr_settings.html
<div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="settings-modal-label" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="settings-modal-label">Map settings</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form method="POST" action="">
          <div class="form-group col-md-12">
            <label class="col-form-label" for="{{ form.title.id_for_label }}">
              Title
            </label>
            <input
              id="{{ form.title.id_for_label }}"
              type="text"
              class="form-control"
              name="{{ form.title.html_name }}"
              value="{{ form.title.value|default:"" }}"
              maxlength="{{ form.title.field.max_length|default:"" }}"
              placeholder="Enter an (optional) map name"
              {% if form.title.field.required %}required{% endif %}
            >
          </div>

          <div class="form-group col-md-12">
            <label class="col-form-label" for="{{ form.layer.id_for_label }}">
              Map colour scheme
            </label>
            <select
              id="{{ form.layer.id_for_label }}"
              class="form-control"
              name="{{ form.layer.html_name }}"
            >
              {% for val, display in form.layer.field.choices %}
              <option
                value="{{ val }}"
                {% if form.layer.value|stringformat:"s" == val|stringformat:"s" %}selected{% endif %}
              >{{ display }}</option>
              {% endfor %}
            </select>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button
          type="button"
          data-url="{% url "maps:xhr-password" map.slug %}"
          class="btn btn-outline-secondary js-password"
          title="Set password"
          {% if map.password %}disabled{% endif %}
        >Set password</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button
          type="button"
          class="btn btn-primary js-save-settings"
          data-url="{% url "maps:xhr-settings" map.slug %}"
        >Save settings</button>
      </div>
    </div>
  </div>
</div>